name: MinezoneCore
main: anthony.SuperCraftBrawl.Core
version: 1.0
commands:
   join:
      description: Join a game
      usage: /join [map name]
   hub:
      description: Hub command
      aliases: h, lobby
   leave:
      description: Leave game command
      aliases: l
   players:
      description: List of players in your game
   gamestats:
      description: Stats after a game
   fly:
      description: Fly command
      aliases: f
   list:
      description: List of online players
   tournament:
      description: Tournament mode
   class:
      description: Class command
   startgame:
      description: Start game
      aliases: sg
   setlevel:
      description: Set level command
   store:
      description: Store command
      aliases: shop, ranks
   nick:
      description: Nickname!
   tell:
      description: Msg command!
      aliases: msg, t, whisper, w, reply, r
   setrank:
      description: Rank command!
      permission: scb.setrank
   setlives:
      description: Set lives command!
   setpoints:
      description: Set points command!
   online:
      description: Online players command!
   purchases:
      description: Purchases command!
   maps:
      description: Displays a list of SCB maps!
      aliases: maplist
   seen:
      description: Seen command
   ignite:
      description: Ignite a player!
   broadcast:
      description: Broadcast command
   spectate:
      description: Spectate command
   socials:
      description: Socials
   vanish:
      description: Vanish
      aliases: v
   unvanish:
      description: Unvanish
   gmc:
      description: Gamemode creative
   gms: 
      description: Gamemode survival
   gma:
      description: Gamemode adventure
   gmsp:
      description: Gamemode spectator
   gm:
      description: General gamemode command
   scbhelp:
      description: Displays SCB help/information
   scb:
      description: Displays SCB help/information
   classes:
      description: Displays list of SCB Classes
   stats:
      description: Player Stats
   token:
      description: Give tokens
   activegames:
      description: Test command
   help:
      description: Sends discord link in chat
      aliases: dc, discord
   sc:
      description: Staff Chat
   staff:
      description: Staff command!
   rules:
      description: Displays the Server Rules
   parkour:
      description: Parkour
   invite:
      description: Invite command
   color:
      description: Color command
   tp:
      description: Teleport command
   world:
      description: World command
   punish:
      description: Punishment command
   exp:
      description: Exp command
   smmtest:
      description: SMM
   sh:
      description: Staff help command
   shr:
      description: Staff help reply command
   points:
      description: Points command
   give:
      description: Give command
   unmute:
      description: Unmute command
   fac:
      description: Test factions command
   sw:
      description: Skywars command
   kit:
      description: Kit command for SkyWars
   items:
      description: Get all SCB Item Drops
      aliases: i
   lactate:
      description: Lactate command!
   sound:
      description: Play a sound on your location
      aliases: s

permissions:
   scb.admin:
      description: Admin perms
      children:
         scb.developer: true
         scb.startGame: true
         scb.setLives: true
         scb.setrank: true
         scb.giveTokens: true
         scb.broadcast: true
         scb.ignite: true
         scb.give: true
         scb.purchases: true
         punish.networkban: true
   scb.developer:
      description: Developer perms
      children:
         scb.builder: true
         scb.items: true
         scb.sound: true
         scb.lactate: true
   scb.builder:
      description: Builder perms
      children:
         scb.moderator: true
         scb.gm: true
         scb.gmc: true
         scb.gms: true
         scb.gmsp: true
         scb.gma: true
   scb.moderator:
      description: Moderator perms
      children:
         scb.trainee: true
         punish.ban: true
         punish.mute: true
   scb.senior_moderator:
      description: Moderator perms
      children:
         scb.trainee: true
         punish.ban: true
         punish.mute: true
   scb.trainee:
      description: Trainee perms
      children:
         scb.captain: true
         scb.vanish: true
         scb.unvanish: true
         scb.staffchat: true
         scb.staff: true
         scb.tp: true
         scb.staffhelp: true
         scb.staffhelpreply: true
         scb.anticheat: true
         minezone.2fa: true
         punish.gui: true
         punish.warning: true
         punish.check: true
         punish.kick: true
   scb.qa:
      description: Design perms
      children:
         scb.captain: true
   scb.media:
      description: Media perms
      children:
         scb.captain: true
   scb.captain:
      description: Captain perms
      children:
         scb.vip: true
         scb.customWin: true
         scb.wheat: true
         scb.invite: true
         scb.color: true
         scb.bypassQueue: true
         scb.customKillMsgs: true
         scb.winEffects: true
         scb.fly: true
   scb.vip:
      description: Vip perms
      children:
         scb.default: true
         scb.nickname.use: true
         scb.bonusTokens: true
         scb.rankBonusOne: true
         scb.rankBonus: true
         scb.cooldown: true
         scb.chat: true
         scb.bypassFull: true
         scb.deathParticles: true
   scb.default:
      description: Default perms
      children:
         
   